### ISSUE TITLE
修改語言檔不生效

### ISSUE THREAD

**Issue by binary3141** [xgpjun/XgpLottery#1]
改了zh_CN.yml 重啟後還是不生效

**Comment by xgpjun** [comment]
你需要在zh_CN.yml中修改对应文本，如果是新建的yml则需要在config中更改文件名。

如果是1.2.0新增的部分文本， 我对此表示抱歉，现在并不能更改。 由于新增的文本有点多，所以完成这些工作需要时间。
我会尽快实现这项功能！
