### ISSUE TITLE
1.20.1 purpur 玩家用/xl shop点击奖池没有出现抽几次界面

### ISSUE THREAD

**Issue by ColdTearsYY** [xgpjun/XgpLottery#2]
如题，1.20.1 purpur端 玩家用/xl shop点击奖池没有出现抽几次界面 只能单抽

**Comment by xgpjun** [comment]
如果设置为givelottery为false。 
在最新版1.2.4中，玩家可以右键抽奖箱打开界面来选择消耗货币 单抽/十连抽  shop只提供购买实体奖券的功能。
