### ISSUE TITLE
关于抽奖lore显示的指令以及抽奖后播报的物品名字

### ISSUE THREAD

**Issue by FxBread** [xgpjun/XgpLottery#3]
![image](https://github.com/xgpjun/XgpLottery/assets/57861523/7bd18ee4-ff46-4e27-a0cf-3f2cd6795ea6)
你好，请问可不可以加一个在抽奖的时候隐藏物品携带的指令集的开关。
![image](https://github.com/xgpjun/XgpLottery/assets/57861523/c7a66c31-049a-43ad-b0f0-8668acabf4fd)

以及不知道为什么抽奖后的名字提示会自动套上物品携带的指令

**Comment by xgpjun** [comment]
虽然过去了很久 但是也没去修改这个东西。
而是重做了本抽奖插件。
